### ISSUE TITLE
Ethereum: INFO Maximum peer count

### ISSUE THREAD

**Issue by nikhilvariar** [mitmedialab/medrec#11]
I ran the following code 

`./medrec-amd64 EthereumClient`

And I'm getting the following error.

`Ethereum: INFO [03-31|14:39:54] Maximum peer count                       ETH=25 LES=0 total=25
Ethereum: INFO [03-31|14:39:54] Starting peer-to-peer node               instance=Geth/v1.8.2-stable-b8b9f7f4/linux-amd64/go1.9.4
Ethereum: INFO [03-31|14:39:54] Allocated cache and file handles         database=/home/user/.medrec/geth/chaindata cache=768 handles=1024
Ethereum: INFO [03-31|14:39:54] Writing default main-net genesis block 
Ethereum: CRIT [03-31|14:39:54] Failed to store block total difficulty   err="leveldb/table: corruption on index-block (pos=80129766): checksum mismatch, want=0xe1ea69b5 got=0x42009153 [file=000729.ldb]"
`

Can someone help me understand the issue ?

**Comment by Firescar96** [comment]
Any log output prefixed with `Ethereum:` is a direct output from a go-ethereum node. I've never seen that error message before, but it's a bug with go-ethereum, not MedRec. It might just go away on it's own.
