### ISSUE TITLE
UserClient exited

### ISSUE THREAD

**Issue by Lu-c-s** [mitmedialab/medrec#15]
Can't run the project, following the production instructions.

I think the EthereumClient and the database manager are running ok...

But I am having this error(UserClient Exited) when running the UserClient(left terminal).

![Capture](https://user-images.githubusercontent.com/23000479/78179263-5073a180-7437-11ea-94fe-b614f2e77dc8.PNG)

Thank you very much in advance.

**Comment by Firescar96** [comment]
This project is somewhat old now (ancient in computer years) and the software packages we used for the UserClient have undergone many breaking changes. I'm not sure what broke with the UserClient and I am no longer working on this project. If you are able to figure it out please submit a pull request.
