### ISSUE TITLE
unable to find package "." even on specifying path

### ISSUE THREAD

**Issue by Rakoshin** [mitmedialab/medrec#18]
Highlighted the issue
![Screenshot (9)](https://user-images.githubusercontent.com/54914036/111692063-04428c80-8855-11eb-96f1-0aa940eece54.png)

**Comment by mr-suroot** [comment]
i dont know go, node... anything
try this:
go mod init medrec
go mod tidy
go build
then follow readme.md

**Comment by Kallirroi** [comment]
This repo is not maintained.
