### ISSUE TITLE
core dumped 

### ISSUE THREAD

**Issue by mr-suroot** [mitmedialab/medrec#19]
node ./GolangJSHelpers/startGeth.js

o/p:
node[12958]: ../src/node_contextify.cc:678:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0x559883450381 node::Abort() [node]
 2: 0x559883450417  [node]
 3: 0x559883441cd6 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [node]
 4: 0x559883696bc7 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [node]
 5: 0x559883697691  [node]
 6: 0x559883697e24  [node]
 7: 0x559883698156 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
 8: 0x559883e66219  [node]
Aborted (core dumped)
#######end
[root@green medrec]# npm -v
6.14.13
[root@green medrec]# node -v
v15.14.0

[root@green medrec]# npm n -v
6.14.13
#######extra
+ @types/secp256k1@4.0.2
npm install github:barrysteyn/node-scrypt#fb60a8d3c158fe115a624b5ffa7480f3a24b03fb

npm install react@15.6.2 react-dom@15.6.2
bitcore-lib@^0.15.0

**Comment by mr-suroot** [comment]
please provide package/apps versions.. that may fix core dump issue

**Comment by Kallirroi** [comment]
Hey - this project is not maintained anymore, sorry.
