### ISSUE TITLE
No build file in GolangJSHelpers

### ISSUE THREAD

**Issue by sathvikask0** [mitmedialab/medrec#4]
there is no build file in  GolangJSHelpers directory.
![screenshot from 2018-10-22 15-40-42](https://user-images.githubusercontent.com/40350207/47287734-e6838580-d610-11e8-9371-0bed3c7fe88e.png)

**Comment by Firescar96** [comment]
there isn't supposed to be

**Comment by Anshdesire** [comment]
Yah then how to follow

Setup the Javascript helper files

$ cd GolangJSHelpers
$ npm install
$ npm run build
$ cd ..

**Comment by Firescar96** [comment]
You don't need to run that line, it looks like a mistake.
