### ISSUE TITLE
GolangJSHelpers/package.json does not contain an command 

### ISSUE THREAD

**Issue by Anshdesire** [mitmedialab/medrec#6]
THere is no command in GolangJSHelpers/package.json so i am not able to run GolangJSHelpers UI

**Comment by Firescar96** [comment]
There is no ui to run, there is not supposed to be any run command. Those files are JS helpers scripts called by some of the golang code.

**Comment by Anshdesire** [comment]
So how to follow these steps 

Setup the Javascript helper files

$ cd GolangJSHelpers
$ npm install
$ npm run build
$ cd ..   

Can you please explain.

**Comment by Firescar96** [comment]
skip the line with `npm run build` I've updated the readme
