### ISSUE TITLE
unable to work on "go build" command in command prompt

### ISSUE THREAD

**Issue by lokeshreddy72** [mitmedialab/medrec#9]

**Comment by lokeshreddy72** [comment]
10:2: cannot find package "github.com/mitmedialab/medrec/DatabaseManager" in any of:
        C:\gocode\bin\src\github.com\mitmedialab\medrec\DatabaseManager (from $GOROOT)
        C:\gocode\src\github.com\mitmedialab\medrec\DatabaseManager (from $GOPATH)

**Comment by Firescar96** [comment]
This is a golang project:
`go get github.com/mitmedialab/medrec`
navigate to the medrec directory in your GOPATH
`go build`
